# Используйте символ § для цветовых кодов
# Список цветовых кодов: https://minecraft.tools/en/color-code.php
# Используйте %name для имени игрока, который вошел в режим невидимости
# Используйте %other-name для имени игрока, который скрыл другого игрока
# Настройка личных сообщений:
# Используйте %sender для отправителя и %message для содержания сообщения

# Не меняйте это!
config-version: 8

# Сообщение, которое увидят игроки при включении невидимости (фейковый выход)
enable-leave: false
FakeLeave-message: "§e%name покинул игру"

# Сообщение, которое увидят игроки при выключении невидимости (фейковый вход)
enable-join: false
FakeJoin-message: "§e%name присоединился к игре"

# Сообщение игроку при выполнении команды /vanish
vanish-message: "§aВы теперь невидимы."
unvanish-message: "§cВы больше не невидимы!"

# Сообщение игрокам с пермишеном vanish.see, когда кто-то входит в ваниш
vanish: "§7§o[%name: Скрылся]"
unvanish: "§7§o[%name: Появился]"

# Сообщение тому, кто скрыл другого игрока
vanish-other: "§aВы скрыли игрока %name"
unvanish-other: "§cВы открыли игрока %name"

# Сообщение игроку, которого скрыл другой игрок
vanished-other: "§aВы теперь невидимы."
unvanished-other: "§cВы больше не невидимы!"

# Сообщение, если невидимый игрок пытается ударить кого-то без прав
hit-no-permission: "§cУ вас нет прав бить других игроков в невидимости"

# HUD сообщение (над панелью быстрого доступа), когда вы в невидимости
hud-message: "§aВы сейчас в невидимости"

# Выключать ли невидимость при выходе с сервера
unvanish-after-leaving: false

# Выключать ли невидимость при перезагрузке сервера
unvanish-after-restart: false

# Разрешить ли невидимым игрокам летать в выживании
enable-fly: true

# Отключить ли получение урона в режиме выживания для невидимых
disable-damage: true

# Сделать ли открытие сундуков бесшумным (сундуки будут только для чтения)
silent-chest: true

# Тратить ли голод в невидимости
hunger: false

# Давать ли эффект ночного зрения невидимым игрокам
night-vision: true

# Скрывать ли обычные сообщения о входе/выходе для игроков с vanish.silent
silent-join-leave:
  join: true
  leave: true
  # Применять это только если игрок уже был в невидимости
  vanished-only: true

# Могут ли обычные игроки писать ЛС невидимым (иначе будет ошибка ниже)
can-send-msg: false
messages:
  sender-error: "Игрок не найден"
  receiver-message: "§c%sender пытался отправить вам сообщение: §7%message"

# Список команд, которые будут заблокированы при использовании на невидимом игроке
# Команды пишутся БЕЗ слеша /
additional-commands:
# Пример
#  tpa:
#    sender-error: "Игрок не найден"
#    receiver-message: "§c%sender пытался отправить вам запрос на телепортацию"
